repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      # - id: pretty-format-json
        # args: ['--no-sort-keys']
      - id: check-symlinks
      - id: debug-statements
      - id: check-xml
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: no-commit-to-branch
        args: [--branch, staging]

  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
