seed : 45

data:
  # All parameters related to the dataset
  path : 'data/ESC-50'
  sample_rate : 8000
  train_folds : [1,2,3]
  val_folds : [4]
  test_folds : [5]
  workers : 20
  batch_size : 8

model:
  # All parameters related to the model
  num_classes : 50
  base_filters : 32
  optimizer:
      # Subset of parameters related to the optimizer
      lr : 3e-4

trainer:
  # All parameters to be passed at the Trainer object
  gpus : 1
  max_epochs : 25

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog