---
name: push-workflow
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  sudo apt-get install -y libsndfile1-dev
            - name: Check with Black formatter
              run: |
                  autoflake --in-place --remove-unused-variables --remove-all-unused-imports --remove-duplicate-keys *.py
                  black --check --diff .
            - name: Run all unit tests
              run: nosetests
